import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { AppShell } from '@/components/AppShell';
import { ResultCard } from '@/components/ResultCard';
import { SectionHeader } from '@/components/SectionHeader';
import { latestResults, teams } from '@/data/demo';
import { colors, radius } from '@/theme';

export default function HomeScreen(){const playoff=teams.slice(0,4);return <AppShell eyebrow="LADIES SEASON 2 · CURRENT" title="The playoffs await." subtitle="Fixtures, verified results, rankings and every Lowveld Padel story in one place.">
  <View style={styles.hero}><View style={styles.pill}><View style={styles.pinkDot}/><Text style={styles.pillText}>PLAYOFF FIELD CONFIRMED</Text></View><Text style={styles.heroTitle}>FOUR TEAMS.{`\n`}ONE CHAMPIONSHIP.</Text><Text style={styles.heroBody}>The regular season built the pressure. Now comes knockout padel.</Text><Pressable style={styles.button} onPress={()=>router.push('/matches')}><Text style={styles.buttonText}>Open Match Centre →</Text></Pressable></View>
  <SectionHeader kicker="QUALIFIED" title="The final four" aside="Season 2"/><View style={styles.table}>{playoff.map((club,index)=><View key={club.id} style={styles.tableRow}><Text style={styles.rank}>{index+1}</Text><Image source={club.logo} style={styles.teamLogo}/><Text style={styles.teamName}>{club.name}</Text><Text style={styles.points}>{club.points}</Text><Text style={styles.pts}>PTS</Text></View>)}</View>
  <SectionHeader kicker="MATCHWEEK 5" title="Latest results" aside="Verified"/>{latestResults.slice(0,2).map(result=><ResultCard result={result} key={result.id}/>)}
</AppShell>}
const styles=StyleSheet.create({hero:{backgroundColor:colors.panel,borderRadius:radius.lg,borderWidth:1,borderColor:'#3a2a55',padding:20,gap:14,overflow:'hidden'},pill:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7,borderRadius:99,borderWidth:1,borderColor:colors.line,paddingHorizontal:10,paddingVertical:7},pinkDot:{width:7,height:7,borderRadius:9,backgroundColor:colors.pink},pillText:{color:colors.text,fontSize:9,fontWeight:'900',letterSpacing:1},heroTitle:{color:colors.text,fontSize:36,fontWeight:'900',lineHeight:37,letterSpacing:-1.5},heroBody:{color:colors.muted,fontSize:14,lineHeight:21},button:{backgroundColor:colors.gold,paddingHorizontal:16,paddingVertical:13,borderRadius:11,alignSelf:'flex-start'},buttonText:{color:'#090d17',fontWeight:'900'},table:{backgroundColor:colors.panel,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,paddingHorizontal:14},tableRow:{flexDirection:'row',alignItems:'center',gap:9,paddingVertical:12,borderBottomWidth:1,borderBottomColor:colors.line},rank:{color:colors.gold,fontWeight:'900',width:16},teamLogo:{width:30,height:30,resizeMode:'contain'},teamName:{color:colors.text,fontWeight:'800',fontSize:13,flex:1},points:{color:colors.text,fontWeight:'900',fontSize:19},pts:{color:colors.muted,fontSize:8,fontWeight:'800'}});
