import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useState } from 'react';
import { AppShell } from '@/components/AppShell';
import { ResultCard } from '@/components/ResultCard';
import { SectionHeader } from '@/components/SectionHeader';
import { latestResults, teams } from '@/data/demo';
import { colors, radius } from '@/theme';
export default function MatchesScreen(){const[tab,setTab]=useState<'results'|'playoffs'>('results');return <AppShell eyebrow="CURRENT COMPETITION" title="Match Centre" subtitle="Ladies Season 2 is current. Completed competitions remain available in the archive.">
  <View style={styles.tabs}><Pressable style={[styles.tab,tab==='results'&&styles.on]} onPress={()=>setTab('results')}><Text style={[styles.tabText,tab==='results'&&styles.onText]}>Latest results</Text></Pressable><Pressable style={[styles.tab,tab==='playoffs'&&styles.on]} onPress={()=>setTab('playoffs')}><Text style={[styles.tabText,tab==='playoffs'&&styles.onText]}>Upcoming playoffs</Text></Pressable></View>
  {tab==='results'?<><SectionHeader kicker="MATCHWEEK 5 · COMPLETE" title="Verified results" aside="3 fixtures"/>{latestResults.map(result=><ResultCard result={result} key={result.id}/>)}</>:<View style={styles.playoff}><Text style={styles.kicker}>UP NEXT · LADIES SEASON 2</Text><Text style={styles.title}>FOUR TEAMS. ONE CHAMPIONSHIP.</Text><Text style={styles.body}>The bracket, match times and venues will appear here as soon as they are confirmed.</Text>{teams.slice(0,4).map((club,i)=><View style={styles.qualifier} key={club.id}><Text style={styles.pos}>{i+1}</Text><Text style={styles.club}>{club.name}</Text><Text style={styles.clubPts}>{club.points} pts</Text></View>)}</View>}
</AppShell>}
const styles=StyleSheet.create({tabs:{flexDirection:'row',backgroundColor:colors.panel,borderRadius:12,padding:4,borderWidth:1,borderColor:colors.line},tab:{flex:1,paddingVertical:11,alignItems:'center',borderRadius:9},on:{backgroundColor:'#1a294b'},tabText:{color:colors.muted,fontWeight:'800',fontSize:12},onText:{color:colors.text},playoff:{backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,borderRadius:radius.lg,padding:20,gap:12},kicker:{color:colors.pink,fontWeight:'900',fontSize:10,letterSpacing:1.4},title:{color:colors.text,fontSize:30,lineHeight:31,fontWeight:'900'},body:{color:colors.muted,lineHeight:21,marginBottom:6},qualifier:{flexDirection:'row',alignItems:'center',gap:12,borderTopWidth:1,borderTopColor:colors.line,paddingTop:12},pos:{color:colors.gold,fontWeight:'900',width:18},club:{color:colors.text,fontWeight:'800',flex:1},clubPts:{color:colors.text,fontWeight:'900'}});
