import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useState } from 'react';
import { AppShell } from '@/components/AppShell';
import { useAuth } from '@/providers/AuthProvider';
import { supabase } from '@/lib/supabase';
import { colors, radius } from '@/theme';
export default function ProfileScreen(){const{session,demoMode}=useAuth();const[email,setEmail]=useState('');const[message,setMessage]=useState('');const signIn=async()=>{if(!supabase){setMessage('Demo mode is active. Connect Supabase to enable player login.');return;}const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:'lowveldpadel://auth/callback'}});setMessage(error?.message||'Check your email for the secure sign-in link.');};return <AppShell eyebrow="PLAYER ACCESS" title="My LP" subtitle="Your player identity, team role, availability and match history.">
  <View style={styles.card}>{session?<><Text style={styles.label}>SIGNED IN</Text><Text style={styles.title}>{session.user.email}</Text><Text style={styles.body}>Your player profile will be linked by league administration.</Text><Pressable style={styles.secondary} onPress={()=>supabase?.auth.signOut()}><Text style={styles.secondaryText}>Sign out</Text></Pressable></>:<><Text style={styles.label}>{demoMode?'DEMO MODE':'SECURE LOGIN'}</Text><Text style={styles.title}>Sign in to your player account</Text><Text style={styles.body}>Use the email registered with Lowveld Padel. No password required.</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="name@email.com" placeholderTextColor={colors.muted} style={styles.input}/><Pressable style={styles.button} onPress={signIn}><Text style={styles.buttonText}>Send secure sign-in link</Text></Pressable>{message&&<Text style={styles.message}>{message}</Text>}</>}</View>
  <View style={styles.roleCard}><Text style={styles.role}>PLAYER</Text><Text style={styles.roleTitle}>Everything about your game.</Text><Text style={styles.body}>Fixtures, results, LP Rating, MVP points, availability and team announcements will live here.</Text></View>
</AppShell>}
const styles=StyleSheet.create({card:{backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,borderRadius:radius.lg,padding:20,gap:12},label:{color:colors.gold,fontSize:9,fontWeight:'900',letterSpacing:1.4},title:{color:colors.text,fontSize:22,fontWeight:'900'},body:{color:colors.muted,fontSize:13,lineHeight:20},input:{backgroundColor:colors.bg,borderWidth:1,borderColor:colors.line,borderRadius:11,paddingHorizontal:14,paddingVertical:13,color:colors.text,fontSize:14},button:{backgroundColor:colors.gold,borderRadius:11,padding:14,alignItems:'center'},buttonText:{color:colors.bg,fontWeight:'900'},message:{color:colors.green,fontSize:12,lineHeight:18},secondary:{borderWidth:1,borderColor:colors.line,borderRadius:11,padding:13,alignItems:'center'},secondaryText:{color:colors.text,fontWeight:'800'},roleCard:{backgroundColor:colors.panelSoft,borderRadius:radius.md,padding:18,gap:7},role:{color:colors.pink,fontSize:9,fontWeight:'900',letterSpacing:1.4},roleTitle:{color:colors.text,fontSize:18,fontWeight:'900'}});
