import { Link } from 'react-router-dom';
import { STANDINGS, franchiseById, legacyFranchiseById } from '../data/seed';
import { LEGACY_LIVE_STANDINGS, LEGACY_LIVE_PLAYERS, LEGACY_LIVE_FIXTURES } from '../data/legacyLive';
import { LADIES_S2_STANDINGS, LADIES_S2_RANKINGS } from '../data/ladiesSeason2Round1Update';
import '../data/ladiesSeason2Matchweek3Update';
import '../styles/home-v3.css';

const LATEST_RESULTS=[{home:'Lunar Lillies',homeScore:11,awayScore:4,away:'Backhand Blossoms'},{home:'Phoenix Flames',homeScore:10,awayScore:3,away:'Desert Roses'},{home:'Net Novas',homeScore:6,awayScore:7,away:'Arctic Angels'}];
const legacyLeader=[...LEGACY_LIVE_STANDINGS].sort((a,b)=>b.points-a.points||b.won-a.won||b.gd-a.gd)[0];
const legacyMvp=[...LEGACY_LIVE_PLAYERS].filter(p=>p.stats?.played>0).sort((a,b)=>b.stats.mvp_points-a.stats.mvp_points||b.stats.wins-a.stats.wins)[0];
const legacyLatest=[...LEGACY_LIVE_FIXTURES].filter(f=>f.status==='final').sort((a,b)=>new Date(b.start)-new Date(a.start))[0];
const channels=[
 {eyebrow:'LADIES FRANCHISE LEAGUE',title:'Lillies light up Matchweek 5.',copy:'Lunar Lillies handed Backhand Blossoms their first defeat of the season with an 11–4 statement win, moving to 44 points.',stat:'11–4',statLabel:'MW5 STATEMENT WIN',to:'/leagues?league=ladies',cta:'Follow Season 2',tone:'blue'},
 {eyebrow:'LADIES FRANCHISE LEAGUE',title:'Blossoms still set the pace.',copy:'Backhand remain top on 53 points, Phoenix Flames move to 39, and Arctic Angels edged Net Novas 7–6 in the Matchweek 5 thriller.',stat:'53',statLabel:'LEAGUE-LEADING POINTS',to:'/leagues?league=ladies',cta:'See every result',tone:'gold'},
 {eyebrow:'LP LEGACY LEAGUE',title:'Built on rivalry. Played for Legacy.',copy:'The Legacy League now has a rebuilt competition hub with the live log, player race, verified results and a dedicated media vault.',stat:String(LEGACY_LIVE_FIXTURES.filter(f=>f.status==='final').length),statLabel:'VERIFIED FIXTURES',to:'/leagues?league=legacy',cta:'Enter Legacy',tone:'red'},
];
const signed=v=>Number(v)>0?`+${v}`:String(v);
const mensLeaders=()=>[...(STANDINGS.mens?.franchise||[])].sort((a,b)=>Number(b.points||0)-Number(a.points||0)).slice(0,3).map(row=>({...row,franchise:franchiseById(row.franchise_id)}));
export default function HomeV3(){const mensTopThree=mensLeaders(),ladiesTop=LADIES_S2_STANDINGS.slice(0,3),mvpTop=LADIES_S2_RANKINGS.slice(0,3);return <main className="hv3">
<section className="hv3-hero"><div className="hv3-hero-copy"><div className="hv3-live-pill"><span/> LOWVELD PADEL · LADIES SEASON 2</div><p className="hv3-overline">MATCHWEEK 5 COMPLETE · THE RUN-IN IS ON</p><h1>FIVE WEEKS IN.<br/><em>THE RACE TIGHTENS.</em></h1><p className="hv3-lead">Lunar Lillies handed the leaders their first defeat, Phoenix Flames powered past Desert Roses and Arctic Angels edged Net Novas by a single point. Matchweek 5 is complete — every point now matters.</p><div className="hv3-actions"><Link to="/leagues?league=ladies" className="hv3-primary">Enter Ladies Season 2</Link><Link to="/leagues?league=legacy">Legacy League</Link></div></div><aside className="hv3-hero-scoreboard"><div className="hv3-scoreboard-head"><span>LADIES SEASON 2</span><b>TOP 3</b></div>{ladiesTop.map((row,index)=><Link className={`hv3-podium-row hv3-podium-${index+1}`} to="/leagues?league=ladies" key={row.id}><span className="hv3-rank">{index+1}</span>{row.logo&&<img src={row.logo} alt=""/>}<span className="hv3-podium-name">{row.name}</span><strong>{row.points}</strong><small>PTS</small></Link>)}<div className="hv3-hero-foot"><span>Matchweek 5 complete</span><Link to="/leagues?league=ladies">Full standings →</Link></div></aside></section>
<section className="hv3-score-strip"><div className="hv3-score-strip-title"><span className="hv3-dot"/><div><b>LADIES · MATCHWEEK 5</b><small>15–16 SEP · FINAL RESULTS</small></div></div>{LATEST_RESULTS.map(r=><div className="hv3-result" key={`${r.home}-${r.away}`}><span>{r.home}</span><strong>{r.homeScore}<i>–</i>{r.awayScore}</strong><span>{r.away}</span></div>)}<Link className="hv3-results-link" to="/leagues?league=ladies">Ladies hub →</Link></section>
<section className="hv3-channel-section"><div className="hv3-section-heading"><div><span className="hv3-kicker">THE SEASON RIGHT NOW</span><h2>Matchweek 5 changes the picture.</h2></div><p>The homepage now brings together the Ladies run-in, the rebuilt Legacy League hub and the completed Men's Season 3 championship.</p></div><div className="hv3-channel-grid">{channels.map(c=><Link to={c.to} className={`hv3-channel hv3-channel-${c.tone}`} key={c.title}><div><span className="hv3-kicker">{c.eyebrow}</span><h3>{c.title}</h3><p>{c.copy}</p></div><div className="hv3-channel-bottom"><div className="hv3-channel-stat"><strong>{c.stat}</strong><span>{c.statLabel}</span></div><b>{c.cta} →</b></div></Link>)}</div></section>
<section className="hv3-split"><div className="hv3-panel hv3-table-panel"><div className="hv3-panel-head"><div><span className="hv3-kicker">LADIES SEASON 2</span><h2>After Matchweek 5</h2></div><Link to="/leagues?league=ladies">Full log →</Link></div><div className="hv3-legacy-table"><div className="hv3-legacy-head"><span>#</span><span>TEAM</span><span>P</span><span>W</span><span>GD</span><span>PTS</span></div>{ladiesTop.map((row,index)=><Link to="/leagues?league=ladies" className={index===0?'hv3-legacy-row is-leader':'hv3-legacy-row'} key={row.id}><span>{index+1}</span><span className="hv3-legacy-team">{row.logo&&<img src={row.logo} alt=""/>}<b>{row.name}</b></span><span>{row.played}</span><span>{row.wins}</span><span className={row.differential>0?'pos':row.differential<0?'neg':''}>{signed(row.differential)}</span><strong>{row.points}</strong></Link>)}</div><p className="hv3-table-note">Official order: accumulated points, set differential, game/points differential, then head-to-head. Week 1 administrative points carry no individual MVP or appearance credit.</p></div><aside className="hv3-panel hv3-feature-panel"><span className="hv3-kicker">LADIES MVP WATCH</span><div className="hv3-feature-number">MVP</div><h2>Five weeks of form.</h2><p>Player rankings update from every verified rubber: 3 points per rubber win plus a bonus point for a clean 4–0.</p><div className="hv3-feature-list">{mvpTop.map((p,i)=><span key={p.id}><b>0{i+1}</b> {p.name} · {p.mvp_points} pts</span>)}</div><Link to="/rankings" className="hv3-primary hv3-wide">Full MVP rankings</Link></aside></section>
<section className="hv3-channel-section"><div className="hv3-section-heading"><div><span className="hv3-kicker">LP LEGACY LEAGUE</span><h2>Legacy has its own stage.</h2></div><p>Live standings, player rankings and every verified result now sit in one competition hub.</p></div><div className="hv3-channel-grid"><Link to="/leagues?league=legacy" className="hv3-channel hv3-channel-gold"><div><span className="hv3-kicker">TABLE LEADER</span><h3>{legacyLeader?legacyFranchiseById(legacyLeader.franchise_id)?.name:'Legacy League'}</h3><p>{legacyLeader?legacyLeader.points+' points · '+legacyLeader.won+' wins · GD '+signed(legacyLeader.gd):'Live standings'}</p></div><div className="hv3-channel-bottom"><b>Full standings →</b></div></Link><Link to="/rankings" className="hv3-channel hv3-channel-blue"><div><span className="hv3-kicker">LEGACY MVP</span><h3>{legacyMvp?.name||'Player rankings'}</h3><p>{legacyMvp?legacyMvp.stats.mvp_points+' MVP points from '+legacyMvp.stats.played+' rubbers.':'Follow the player race.'}</p></div><div className="hv3-channel-bottom"><b>Player race →</b></div></Link><Link to="/leagues?league=legacy" className="hv3-channel hv3-channel-red"><div><span className="hv3-kicker">LATEST VERIFIED RESULT</span><h3>{legacyLatest?legacyFranchiseById(legacyLatest.home)?.name+' '+legacyLatest.score.totals[0]+'–'+legacyLatest.score.totals[1]+' '+legacyFranchiseById(legacyLatest.away)?.name:'Results'}</h3><p>Results feed directly into the live table and individual statistics.</p></div><div className="hv3-channel-bottom"><b>Results & gallery →</b></div></Link></div></section>
<section className="hv3-data-row"><article><span className="hv3-kicker">MATCHWEEK 5</span><strong>11–4</strong><p>Lunar Lillies handed Backhand Blossoms their first defeat.</p></article><article><span className="hv3-kicker">CLOSEST TIE</span><strong>7–6</strong><p>Arctic Angels edged Net Novas by a single point.</p></article><article><span className="hv3-kicker">PHOENIX</span><strong>10–3</strong><p>The Flames took three of four rubbers against Desert Roses.</p></article><article><span className="hv3-kicker">MEN'S CHAMPIONS</span><strong>{mensTopThree.length?'FALCONS':'—'}</strong><p>Season 3 champions after the 14–8 Grand Final.</p></article></section>
<section className="hv3-cta-band"><div><span className="hv3-kicker">LADIES FRANCHISE LEAGUE · SEASON 2</span><h2>Follow every Lowveld Padel competition.</h2></div><div className="hv3-actions"><Link to="/leagues?league=ladies" className="hv3-primary">Ladies league</Link><Link to="/rankings">MVP rankings</Link><Link to="/live">Match centre</Link><Link to="/tv">Lowveld TV</Link></div></section></main>;
}
