import { Link } from 'react-router-dom';
import { STANDINGS, franchiseById, legacyFranchiseById } from '../data/seed';
import { LEGACY_LIVE_STANDINGS } from '../data/legacyLive';
import { LADIES_S2_STANDINGS, LADIES_S2_RANKINGS } from '../data/ladiesSeason2Round1Update';
import '../data/ladiesSeason2Matchweek3Update';
import '../styles/home-v3.css';

const LATEST_RESULTS=[{home:'Backhand Blossoms',homeScore:14,awayScore:0,away:'Desert Roses'},{home:'Phoenix Flames',homeScore:11,awayScore:3,away:'Net Novas'},{home:'Arctic Angels',homeScore:8,awayScore:7,away:'Lunar Lillies'}];
const channels=[
 {eyebrow:'LADIES FRANCHISE LEAGUE',title:'Blossoms take control.',copy:'Backhand Blossoms produced the statement result of Matchweek 3, sweeping Desert Roses 14–0 as the Season 2 title race enters its decisive phase.',stat:'14–0',statLabel:'MW3 STATEMENT WIN',to:'/leagues?league=ladies',cta:'Follow Season 2',tone:'blue'},
 {eyebrow:'LADIES FRANCHISE LEAGUE',title:'Flames surge. Angels survive.',copy:'Phoenix Flames powered past Net Novas 11–3, while Arctic Angels edged Lunar Lillies 8–7 in the closest tie of the week.',stat:'8–7',statLabel:'ONE-POINT THRILLER',to:'/leagues?league=ladies',cta:'See every result',tone:'gold'},
 {eyebrow:"MEN'S FRANCHISE LEAGUE",title:'Falcons reign as champions.',copy:'Season 3 is complete after Desert Falcons beat two-time champions Sonic Viboras 14–8 in the Grand Final.',stat:'14–8',statLabel:'GRAND FINAL',to:'/leagues?league=mens',cta:'Season 3 archive',tone:'red'},
];
const signed=v=>Number(v)>0?`+${v}`:String(v);
const mensLeaders=()=>[...(STANDINGS.mens?.franchise||[])].sort((a,b)=>Number(b.points||0)-Number(a.points||0)).slice(0,3).map(row=>({...row,franchise:franchiseById(row.franchise_id)}));
export default function HomeV3(){const mensTopThree=mensLeaders(),ladiesTop=LADIES_S2_STANDINGS.slice(0,3),mvpTop=LADIES_S2_RANKINGS.slice(0,3);return <main className="hv3">
<section className="hv3-hero"><div className="hv3-hero-copy"><div className="hv3-live-pill"><span/> LOWVELD PADEL · LADIES SEASON 2</div><p className="hv3-overline">MATCHWEEK 3 COMPLETE · THE RUN-IN STARTS NOW</p><h1>THE TITLE RACE<br/><em>JUST GOT SERIOUS.</em></h1><p className="hv3-lead">Backhand Blossoms delivered a 14–0 statement, Phoenix Flames surged past Net Novas and Arctic Angels won an 8–7 thriller. Three matchweeks down — every point now carries playoff pressure.</p><div className="hv3-actions"><Link to="/leagues?league=ladies" className="hv3-primary">Enter Ladies Season 2</Link><Link to="/rankings">Ladies MVP race</Link></div></div><aside className="hv3-hero-scoreboard"><div className="hv3-scoreboard-head"><span>LADIES SEASON 2</span><b>TOP 3</b></div>{ladiesTop.map((row,index)=><Link className={`hv3-podium-row hv3-podium-${index+1}`} to="/leagues?league=ladies" key={row.id}><span className="hv3-rank">{index+1}</span>{row.logo&&<img src={row.logo} alt=""/>}<span className="hv3-podium-name">{row.name}</span><strong>{row.points}</strong><small>PTS</small></Link>)}<div className="hv3-hero-foot"><span>Matchweek 3 complete</span><Link to="/leagues?league=ladies">Full standings →</Link></div></aside></section>
<section className="hv3-score-strip"><div className="hv3-score-strip-title"><span className="hv3-dot"/><div><b>LADIES · MATCHWEEK 3</b><small>1–2 SEP · FINAL RESULTS</small></div></div>{LATEST_RESULTS.map(r=><div className="hv3-result" key={`${r.home}-${r.away}`}><span>{r.home}</span><strong>{r.homeScore}<i>–</i>{r.awayScore}</strong><span>{r.away}</span></div>)}<Link className="hv3-results-link" to="/leagues?league=ladies">Ladies hub →</Link></section>
<section className="hv3-channel-section"><div className="hv3-section-heading"><div><span className="hv3-kicker">THE SEASON RIGHT NOW</span><h2>Matchweek 3 changes the picture.</h2></div><p>The old Matchweek 2 story is gone. The homepage now follows the current Ladies title race, MVP battle and latest verified results.</p></div><div className="hv3-channel-grid">{channels.map(c=><Link to={c.to} className={`hv3-channel hv3-channel-${c.tone}`} key={c.title}><div><span className="hv3-kicker">{c.eyebrow}</span><h3>{c.title}</h3><p>{c.copy}</p></div><div className="hv3-channel-bottom"><div className="hv3-channel-stat"><strong>{c.stat}</strong><span>{c.statLabel}</span></div><b>{c.cta} →</b></div></Link>)}</div></section>
<section className="hv3-split"><div className="hv3-panel hv3-table-panel"><div className="hv3-panel-head"><div><span className="hv3-kicker">LADIES SEASON 2</span><h2>After Matchweek 3</h2></div><Link to="/leagues?league=ladies">Full log →</Link></div><div className="hv3-legacy-table"><div className="hv3-legacy-head"><span>#</span><span>TEAM</span><span>P</span><span>W</span><span>GD</span><span>PTS</span></div>{ladiesTop.map((row,index)=><Link to="/leagues?league=ladies" className={index===0?'hv3-legacy-row is-leader':'hv3-legacy-row'} key={row.id}><span>{index+1}</span><span className="hv3-legacy-team">{row.logo&&<img src={row.logo} alt=""/>}<b>{row.name}</b></span><span>{row.played}</span><span>{row.wins}</span><span className={row.differential>0?'pos':row.differential<0?'neg':''}>{signed(row.differential)}</span><strong>{row.points}</strong></Link>)}</div><p className="hv3-table-note">Official order: accumulated points, fixture wins, GD, then SD. Week 1 administrative points carry no individual MVP or appearance credit.</p></div><aside className="hv3-panel hv3-feature-panel"><span className="hv3-kicker">LADIES MVP WATCH</span><div className="hv3-feature-number">MVP</div><h2>Three weeks of form.</h2><p>Player rankings update from every verified rubber: 3 points per rubber win plus a bonus point for a clean 4–0.</p><div className="hv3-feature-list">{mvpTop.map((p,i)=><span key={p.id}><b>0{i+1}</b> {p.name} · {p.mvp_points} pts</span>)}</div><Link to="/rankings" className="hv3-primary hv3-wide">Full MVP rankings</Link></aside></section>
<section className="hv3-data-row"><article><span className="hv3-kicker">MATCHWEEK 3</span><strong>14–0</strong><p>Backhand Blossoms delivered the week's clean sweep.</p></article><article><span className="hv3-kicker">CLOSEST TIE</span><strong>8–7</strong><p>Arctic Angels edged Lunar Lillies by a single point.</p></article><article><span className="hv3-kicker">PHOENIX</span><strong>11–3</strong><p>The Flames took three of four rubbers against Net Novas.</p></article><article><span className="hv3-kicker">MEN'S CHAMPIONS</span><strong>{mensTopThree.length?'FALCONS':'—'}</strong><p>Season 3 champions after the 14–8 Grand Final.</p></article></section>
<section className="hv3-cta-band"><div><span className="hv3-kicker">LADIES FRANCHISE LEAGUE · SEASON 2</span><h2>Three weeks down. Follow the run-in.</h2></div><div className="hv3-actions"><Link to="/leagues?league=ladies" className="hv3-primary">Ladies league</Link><Link to="/rankings">MVP rankings</Link><Link to="/live">Match centre</Link><Link to="/tv">Lowveld TV</Link></div></section></main>}