import { Link } from 'react-router-dom';
import { FRANCHISES, STANDINGS, franchiseById, legacyFranchiseById } from '../data/seed';
import { LEGACY_LIVE_STANDINGS } from '../data/legacyLive';
import { LADIES_S2_STANDINGS, LADIES_S2_RANKINGS } from '../data/ladiesSeason2Round1Update';
import '../styles/home-v3.css';

const TODAY_RESULTS=[{home:'Backhand Blossoms',homeScore:15,awayScore:0,away:'Phoenix Flames'},{home:'Lunar Lillies',homeScore:11,awayScore:4,away:'Net Novas'},{home:'Desert Roses',homeScore:4,awayScore:9,away:'Arctic Angels'}];
const channels=[
 {eyebrow:'LP LEGACY',title:'The playoffs are here.',copy:'The league phase is done. Cheetahs earned the No. 1 seed on 36 points, but now the table disappears and knockout pressure takes over.',stat:'36',statLabel:'PTS · #1 CHEETAHS',to:'/leagues?league=legacy',cta:'Enter playoff race',tone:'gold'},
 {eyebrow:'LADIES FRANCHISE LEAGUE',title:'Blossoms and Lillies set the pace.',copy:'Two matchweeks in and both are unbeaten. Backhand Blossoms lead on 23 points, just one ahead of Lunar Lillies.',stat:'23–22',statLabel:'TOP TWO · 1 PT GAP',to:'/leagues?league=ladies',cta:'Follow Season 2',tone:'blue'},
 {eyebrow:"MEN'S FRANCHISE LEAGUE",title:'Falcons reign as champions.',copy:'Season 3 is in the books after Desert Falcons beat two-time champions Sonic Viboras 14–8 in the Grand Final.',stat:'14–8',statLabel:'GRAND FINAL',to:'/leagues?league=mens',cta:'Season 3 archive',tone:'red'},
];
const signed=v=>Number(v)>0?`+${v}`:String(v);
const legacyRows=()=>[...LEGACY_LIVE_STANDINGS].map(row=>({...row,franchise:legacyFranchiseById(row.franchise_id)}));
const mensLeaders=()=>[...(STANDINGS.mens?.franchise||[])].sort((a,b)=>Number(b.points||0)-Number(a.points||0)).slice(0,3).map(row=>({...row,franchise:franchiseById(row.franchise_id)}));
export default function HomeV3(){const legacy=legacyRows(),topThree=legacy.slice(0,3),mensTopThree=mensLeaders(),mensCount=FRANCHISES.filter(f=>f.league==='mens').length,ladiesTop=LADIES_S2_STANDINGS.slice(0,3),mvpTop=LADIES_S2_RANKINGS.slice(0,3);return <main className="hv3">
<section className="hv3-hero"><div className="hv3-hero-copy"><div className="hv3-live-pill"><span/> LOWVELD PADEL · 27 AUGUST 2026</div><p className="hv3-overline">LP LEGACY LEAGUE · PLAYOFF MODE</p><h1>THE TABLE IS DONE.<br/><em>NOW SURVIVE.</em></h1><p className="hv3-lead">Cheetahs take the No. 1 seed into the Legacy playoffs after finishing on 36 points. The regular season built the story. The knockout stage decides the legacy.</p><div className="hv3-actions"><Link to="/leagues?league=legacy" className="hv3-primary">Legacy playoff centre</Link><Link to="/rankings">Player rankings</Link></div></div><aside className="hv3-hero-scoreboard"><div className="hv3-scoreboard-head"><span>PLAYOFF SEEDING</span><b>TOP 3</b></div>{topThree.map((row,index)=><Link className={`hv3-podium-row hv3-podium-${index+1}`} to={`/legacy-franchise/${row.franchise_id}`} key={row.franchise_id}><span className="hv3-rank">{index+1}</span>{row.franchise?.logo&&<img src={row.franchise.logo} alt=""/>}<span className="hv3-podium-name">{row.franchise?.name||row.franchise_id}</span><strong>{row.points}</strong><small>PTS</small></Link>)}<div className="hv3-hero-foot"><span>League phase complete · playoffs next</span><Link to="/leagues?league=legacy">Full table →</Link></div></aside></section>
<section className="hv3-score-strip"><div className="hv3-score-strip-title"><span className="hv3-dot"/><div><b>LADIES · MATCHWEEK 2</b><small>26 AUG · FINAL RESULTS</small></div></div>{TODAY_RESULTS.map(r=><div className="hv3-result" key={`${r.home}-${r.away}`}><span>{r.home}</span><strong>{r.homeScore}<i>–</i>{r.awayScore}</strong><span>{r.away}</span></div>)}<Link className="hv3-results-link" to="/leagues?league=ladies">Ladies hub →</Link></section>
<section className="hv3-channel-section"><div className="hv3-section-heading"><div><span className="hv3-kicker">YOUR LEAGUES</span><h2>Three competitions. One Lowveld.</h2></div><p>Legacy hits knockout mode while Ladies Season 2 gathers momentum.</p></div><div className="hv3-channel-grid">{channels.map(c=><Link to={c.to} className={`hv3-channel hv3-channel-${c.tone}`} key={c.title}><div><span className="hv3-kicker">{c.eyebrow}</span><h3>{c.title}</h3><p>{c.copy}</p></div><div className="hv3-channel-bottom"><div className="hv3-channel-stat"><strong>{c.stat}</strong><span>{c.statLabel}</span></div><b>{c.cta} →</b></div></Link>)}</div></section>
<section className="hv3-split"><div className="hv3-panel hv3-table-panel"><div className="hv3-panel-head"><div><span className="hv3-kicker">LADIES SEASON 2</span><h2>After Matchweek 2</h2></div><Link to="/leagues?league=ladies">Full log →</Link></div><div className="hv3-legacy-table"><div className="hv3-legacy-head"><span>#</span><span>TEAM</span><span>P</span><span>W</span><span>GD</span><span>PTS</span></div>{ladiesTop.map((row,index)=><Link to="/leagues?league=ladies" className={index===0?'hv3-legacy-row is-leader':'hv3-legacy-row'} key={row.id}><span>{index+1}</span><span className="hv3-legacy-team"><b>{row.name}</b></span><span>{row.played}</span><span>{row.wins}</span><span className={row.differential>0?'pos':row.differential<0?'neg':''}>{signed(row.differential)}</span><strong>{row.points}</strong></Link>)}</div><p className="hv3-table-note">Official order: accumulated points, fixture wins, GD, then SD. Week 1 administrative points carry no individual MVP or appearance credit.</p></div><aside className="hv3-panel hv3-feature-panel"><span className="hv3-kicker">LADIES MVP WATCH</span><div className="hv3-feature-number">MVP</div><h2>Every rubber matters.</h2><p>Player rankings are calculated from verified results only: 3 points per rubber win plus a bonus point for a clean 4–0.</p><div className="hv3-feature-list">{mvpTop.map((p,i)=><span key={p.id}><b>0{i+1}</b> {p.name} · {p.mvp_points} pts</span>)}</div><Link to="/rankings" className="hv3-primary hv3-wide">Full MVP rankings</Link></aside></section>
<section className="hv3-data-row"><article><span className="hv3-kicker">LEGACY #1 SEED</span><strong>36</strong><p>Cheetahs points after five regular-season fixtures.</p></article><article><span className="hv3-kicker">LADIES LEADER</span><strong>23</strong><p>Backhand Blossoms lead Lunar Lillies by a single point.</p></article><article><span className="hv3-kicker">UNBEATEN</span><strong>2</strong><p>Blossoms and Lillies are both 2–0 after Matchweek 2.</p></article><article><span className="hv3-kicker">MEN'S CHAMPIONS</span><strong>{mensTopThree.length? 'FALCONS':'—'}</strong><p>Season 3 champions after the 14–8 Grand Final.</p></article></section>
<section className="hv3-cta-band"><div><span className="hv3-kicker">LOWVELD PADEL</span><h2>Legacy playoffs. Ladies title race. One home for all of it.</h2></div><div className="hv3-actions"><Link to="/live" className="hv3-primary">Match centre</Link><Link to="/rankings">Rankings</Link><Link to="/tv">Lowveld TV</Link><Link to="/community">Community</Link></div></section></main>}
