import { Link } from 'react-router-dom';

export default function Privacy(){
 const sections=[
 ['1. Who we are','Lowveld Padel organises padel leagues, ranking events, cups, community competitions and related activities. For personal information collected through this website and Lowveld Padel registration processes, Lowveld Padel acts as the responsible party for purposes of the Protection of Personal Information Act 4 of 2013 (POPIA).'],
 ['2. Information we may collect','Depending on the activity, we may collect a participant’s name, surname, mobile number, email address, date of birth, gender, profile/player photograph, current team or franchise, registration and participation information, match results, rankings, statistics, disciplinary or eligibility records where necessary, payment/transaction status, communications with Lowveld Padel, and technical information generated when using our website. We aim to collect only information reasonably necessary for the stated purpose.'],
 ['3. Why we process information','We process personal information to administer registrations; identify and communicate with players; organise leagues, ranking series, cups, fixtures and events; determine eligibility and age categories; maintain results, rankings, player records and statistics; publish sporting results and approved player profiles; manage payments where applicable; communicate operational information; administer prizes and awards; maintain the integrity and safety of competitions; improve our services and website; meet legal, regulatory, accounting or dispute-resolution requirements; and protect the legitimate interests of Lowveld Padel and participants.'],
 ['4. Player photographs, results and rankings','Where appropriate and lawful, Lowveld Padel may display a player’s name, team/franchise, photograph, match results, rankings, statistics, awards and competition-related content on Lowveld Padel channels, including its website and social-media or event communications. Private contact details, dates of birth and other non-public registration information will not ordinarily be published.'],
 ['5. Children and junior players','A participant under 18 is a child for POPIA purposes. Where consent is relied upon to process a child’s personal information, registration and consent must be completed or authorised by a parent, legal guardian or other competent person legally entitled to consent for the child. Lowveld Padel will seek to collect no more information about junior players than is reasonably necessary and will apply additional care to its use, access and publication.'],
 ['6. Storage and service providers','Information may be stored using reputable technology and cloud-service providers used to operate Lowveld Padel, which may include website hosting, Google services such as Google Sheets/Drive, email, database, analytics or similar operational platforms. Such providers may process information on Lowveld Padel’s behalf. Reasonable organisational and technical safeguards will be used to limit unauthorised access, loss, misuse, alteration or disclosure.'],
 ['7. Sharing of information','We do not sell player personal information. Information may be shared only where reasonably necessary with authorised Lowveld Padel administrators, competition officials, venues or operational partners, contracted technology/service providers, professional advisers, or authorities where required or permitted by law. Public sporting information may be shared as described above.'],
 ['8. Cross-border processing','Some cloud or technology providers may store or process information outside South Africa. Where this occurs, Lowveld Padel will seek to use reputable providers and handle cross-border processing consistently with applicable POPIA requirements.'],
 ['9. Retention','Personal information will be kept only for as long as reasonably necessary for the purpose for which it was collected, for legitimate sporting and historical records, or as required by law. Information that is no longer required will be deleted, destroyed or de-identified where reasonably practicable. Competition results and historical sporting records may be retained for archival, statistical and historical purposes.'],
 ['10. Your rights','Subject to applicable law, you may ask whether Lowveld Padel holds personal information about you, request access to it, ask that inaccurate information be corrected or deleted where appropriate, object to certain processing, withdraw consent where consent is the legal basis for processing, or raise a concern about how your information is handled. Withdrawal of consent does not invalidate lawful processing that occurred before withdrawal and may affect participation where the information is necessary to administer a competition.'],
 ['11. Security compromises','If Lowveld Padel becomes aware of a security compromise involving personal information, it will take reasonable steps to investigate, contain and respond to the incident and make notifications where required by POPIA.'],
 ['12. Cookies and website data','The website may use essential browser storage, cookies or similar technologies required for functionality and may use limited analytics or performance information. We will not intentionally use such technologies to collect more personal information than is reasonably necessary for operating and improving the site.'],
 ['13. Changes to this notice','This Privacy & POPIA Notice may be updated as Lowveld Padel’s competitions, systems or legal obligations evolve. The current version will be published on this website.'],
 ['14. Contact and complaints','Questions, requests or objections concerning personal information should be directed to Lowveld Padel through its published contact channels. A data subject also has the right to lodge a complaint with the Information Regulator (South Africa) if they believe their personal information has been processed unlawfully.']
 ];
 return <div className="page" style={{maxWidth:900}}><span className="chip">Privacy · POPIA</span><h1 className="display" style={{marginTop:12}}>Privacy & POPIA Notice</h1><p className="muted" style={{lineHeight:1.7}}>Effective 6 September 2026 · This notice explains how Lowveld Padel collects, uses, stores, shares and protects personal information.</p><div className="card" style={{padding:22,margin:'20px 0',borderTop:'3px solid var(--gold)'}}><strong>Our privacy commitment</strong><p className="muted" style={{lineHeight:1.7,marginBottom:0}}>Lowveld Padel respects the privacy of its players, parents, supporters, officials and partners. We process personal information for legitimate and defined sporting and operational purposes and seek to handle it responsibly, transparently and securely.</p></div>{sections.map(([h,b])=><section key={h} style={{margin:'28px 0'}}><h2 className="display" style={{fontSize:19}}>{h}</h2><p className="muted" style={{lineHeight:1.75}}>{b}</p></section>)}<div className="card" style={{padding:20,marginTop:30}}><b>Registration consent</b><p className="muted" style={{lineHeight:1.65}}>Competition registration forms may require a specific POPIA acknowledgement before submission. For a participant under 18, the competent person providing consent confirms that they are legally entitled to do so.</p><Link to="/register" className="btn" style={{display:'inline-block',marginTop:6}}>Registration</Link></div></div>;
}